title: Competitive Programming With Chathur
author: Chathur Gudesa
theme: minima
email: chathurgudesa93760@gmail.com
description: > # this means to ignore newlines until "baseurl:"
I am going to write about stuff related to competitive programming on this blog.
# social links

twitter_username: chathur_gudesa # DO NOT include the @ character, or else the build will fail!
github_username:  grandesonnerie # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
